### PR TITLE
Website and first tutorials

### PR DESCRIPTION
**Pull request by OceanWolf**
Voila, a first version of a tutorial website that requires no maintenance, it just needs a bit of styling.

I will finish the tutorials once we have this PR in, then I can use this tutorial as the example used in the tutorial... yes recursion, best not to think about it ;).

### CODE REVIEW

**Comment by aoloe** [comment]
hey

before integrating your pull request, we should solve the license issue.

it's ok for you to change it to cc-by-sa?

https://creativecommons.org/licenses/by-sa/2.0/

ciao
a.l.e

**Comment by OceanWolf** [comment]
I don't really know the differences tbh.

Also note I PR this against the new branch I created, `gh-pages` so it doesn't have the license thing in here.  All pushes to this branch go to http://scribus.io/scribus-tutorials/.

Perhaps fine to just add as a plain text file as in the master of this branch?  I foresee us deleting the master branch here in due course.

**Comment by aoloe** [comment]
i'll change the license to cc-by-sa, then.

but, please, don't remove the master directory.

people are used to see one...

**Comment by OceanWolf** [comment]
Of course I won't remove the "master branch" now, but in the future I think it should go.

What do you mean by "people are used to see one"?  I think most people won't notice that we don't have one...

As a first step though I would like to change the default branch to this branch, hopefully tomorrow, but if we need further discussion on that, I don't mind arguing the case for it.

@luzpaz your thoughts?  Anyone else we should bring into this?

**Comment by luzpaz** [comment]
Just add the license and we are green light

**Comment by OceanWolf** [comment]
Can you send me a copy of the license?  Or even add the license yourself into the `gh-pages` branch?

**Comment by luzpaz** [comment]
@aoloe do you mind adding the license after I accept the PR? Thanks!

**Comment by aoloe** [comment]
the cc-by-sa is now in! :-)

**Pull request merged**
